<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Root [
<!ELEMENT Root (Customers)>
<!ELEMENT Customers (Customer+)>
<!ELEMENT Customer (CompanyName, ContactName, ContactTitle, Phone, FullAddress)>
<!ATTLIST Customer CustomerID ID #REQUIRED>
<!ELEMENT CompanyName (#PCDATA)>
<!ELEMENT ContactName (#PCDATA)>
<!ELEMENT ContactTitle (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT FullAddress (Address, City, Region, PostalCode, Country)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT PostalCode (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
]>
<?xml version="1.0" encoding="utf-8"?>
<Root>
  <Customers>
    <Customer CustomerID="GREAL">
      <CompanyName>Great Lakes Food Market</CompanyName>
      <ContactName>Howard Snyder</ContactName>
      <ContactTitle>Marketing Manager</ContactTitle>
      <Phone>(503) 555-7555</Phone>
      <FullAddress>
        <Address>2732 Baker Blvd.</Address>
        <City>Eugene</City>
        <Region>OR</Region>
        <PostalCode>97403</PostalCode>
        <Country>USA</Country>
      </FullAddress>
    </Customer>
  </Customers>
</Root>
